### PR TITLE
Multiple small updates

### PR DESCRIPTION
**Pull request by glederrey**
Hi,
Following the issues that I had (issue #17), I update the file `table_evaluator.py`. Here are the changes:
-  **Remove the `numerical_encoding` function:** It was creating one-hot encoding for all the categorical variables. It thus created a sparse matrix. And I think the inconsistencies that I got were coming from this issue. 
- **Update the function `convert_numerical`:** I updated this function to simply deal with categories written as strings (since it seemed to be the main issue of the code). I'm using the `factorize` function from `pandas` to replace the string values with integers.
- **Use the `convert_numerical` function when needed:** You had duplicate code when you needed to encode the dataset. I thus removed these parts and simply called the function `convert_numerical` instead. 
- **Add PCA similarity score back:** I simply added the PCA similarly score back. I don't know why you removed it. Maybe you might want to remove it again. But the results were interesting for me. =)

That's all the changes I've made to your code. It shouldn't have any issues with inconsistent results now. But if there are any issues, please let me know and I will have a look at it. =)

### CODE REVIEW

**Comment by Baukebrenninkmeijer** [comment]
@glederrey Thanks for the PR. Some very good stuff. To answer some questions/raise some points. 
1. Numerical encoding was using one-hot-encoding for categorical columns with more than 2 values, because for most/all distance measure, you introduce arbitrary distance between values if you just factorize. That's why we can only use one-hot encoding in that location. I think this only goes for `row_distance`, so if you re-add it for that function but use factorize for the others, I think it should be ok. 

To clarify, the distance in your code is 
```
nearest neighbor mean                    0.5580
nearest neighbor std                     0.3509
```

While on develop i get:
``` 
nearest neighbor mean                    0.5655
nearest neighbor std                       0.3726
```
2. Regarding PCA, one current issue is that both datasets fit their own PCA model. To actually compare the results, we should train PCA on one dataset and transform both with those values. Additionally, PCA gets really easy skewed by large numbers. So with large numbers in a dataset, the small values don't really matter anymore. That's why I removed it from the actual report output, because I didn't think it actually reflected the similarity that well. I think the plots can still offer some insights, but should also be considered very carefully. 


Hope this helps. You raise some good points, so if you can address these two changes, I'll be happy to merge your PR.

Furthermore, thank you for your patience for my response :)

**Review by Baukebrenninkmeijer — CHANGES_REQUESTED** [review]
Good stuff, two small things still need addressing.

**Comment by glederrey** [comment]
@Baukebrenninkmeijer Thanks a lot for the clarification. 

1. I see the issue with the distance. The best would be to have a distinction between categorical and ordinal data types. Since the idea of distance works for ordinal data but it does not make sense for categorical data. But it's definitely something for the future =)
2. I see the issue with PCA. I was playing with something like this when doing my own evaluation. And it's true that it was not super consistent.

I will update it on my repo and make another pull request. =)

**Comment by glederrey** [comment]
I made the update. I added a function `numerical_encoding_one_hot` that is the old `numerical_encoding` function. The new function is used in the function `row_distance` as requested. I also removed the PCA results. =)

**Comment by Baukebrenninkmeijer** [comment]
@glederrey Indeed, a distinction between ordinal and categorical data would be the ideal solution. However, this is often hard to do or requires a lot of manual work, so for the most consistent yet easy approach I opted for this.

**Comment by glederrey** [comment]
@Baukebrenninkmeijer Yeah, I'm currently investigating new validation techniques that will take this into account. But it's a lot more complicated than expected. =)

I just added a boolean parameter to make the KFold CV optional. =)

**Comment by Baukebrenninkmeijer** [comment]
@glederrey I see that you've put the output in evaluate within the `if verbose` section. I think those should be enabled by default, since it shows useful information. Because it's not being returned by `all_results`, there's also not a non-verbose way of showing this information. We could add a toggle to hide it, but it doesn't qualify as verbose imo. 

However, I'm also not looking forward to having a `verbose`, a `hide_output` and a `notebook` toggle, that feels like overkill. Ideally, I'd just want the output to be there by default. 

What we could do is add the other values to `all_results`, and make sure everything is returned from the useful information. We can then have a toggle that says `return_values` or smthing like that. `verbose` really is for details during running, so that you can really track what's happening, not for just showing the results.

**Comment by Baukebrenninkmeijer** [comment]
Thanks for the docstring addition btw :)

**Comment by glederrey** [comment]
In my very specific case, I'm running your code on 725 different datasets. So, printing the results creates a lot of "noise". That's why I added it in the verbose. But I agree that the final results should not be in the verbose. 

If the notebook output is already printing stuff, we could simply remove the prints. (I have no idea how it would work if launched from the terminal though) If not, then I will revert the code to its previous state. I agree that adding another flag to hide the output would be overkill. (There are always ways to redirect the sys.stdout to a file or whatever to hide it in the worst case) 

However, I think it's important to output the results in a variables for better systematic results. 

Let me know what you think and I will update the code accordingly. =)

Btw, I will have to cite your evaluator in my article. So, should I cite your master thesis? Or have you published an article following your master thesis?

**Comment by Baukebrenninkmeijer** [comment]
@glederrey 
The notebook section is really meant for notebook situation, and shouldn't be expected to be the default imo. I did also built in a function to automatically detect jupyter environments, so that could help a bit there. 

725 datasets is indeed a lot, hahaha. I understand where you are coming from now. 😄 

I think i'll have a look myself at returning all the needed information. Regarding hiding the output for now, could you just change that locally for now? I think I will eventually solve it with the `return_values` flag, as mentioned. That's fairly clean, and more often used in parallel with verbose.

**Comment by glederrey** [comment]
Okay, I see. And I agree with you. 
I will then revert back to printing by default and remove it locally =)

I'll do the commit tomorrow morning.

**Comment by Baukebrenninkmeijer** [comment]
@glederrey regarding your other question:
> Btw, I will have to cite your evaluator in my article. So, should I cite your master thesis? Or have you published an article following your master thesis?

I have unfortunately not followed up with anything, so you can cite my thesis :).

**Pull request merged**
